version: '3.1'

services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: shariasource-rails
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    # command: bundle exec rails s -p 3001 -b '0.0.0.0'
    # command: tail -F anything
    environment:
      MIGRATE: "False"
      CREATE_ADMIN: "False"
      RAILS_ENV: development
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres_pw
      DATABASE_URL: postgres://postgres:postgres_pw@db:5432/shariasource_local
  
  db:
    image: postgres:12.15-alpine
    container_name: shariasource-db
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pw
      POSTGRES_DB: shariasource_local

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}