source 'https://rubygems.org'
ruby '2.4.1'

gem 'active_attr', '~> 0.8.4'
gem 'autoprefixer-rails', '~> 7.1.0'
gem 'carrierwave', '~> 1.1'
gem 'chosen-rails', '~> 1.1.0'
gem 'closure_tree'
gem 'coffee-rails', '~> 4.0.0'
gem 'devise', '~> 4.3'
gem 'foreman', '~> 0.74.0'
gem 'foundation-rails', '~> 5.5.0'
gem 'pdf-reader', '~> 1.4.0'
gem 'hijri_gem', '~> 0.4.2'
gem 'jquery-rails', '~> 4.3'
gem 'jquery-ui-rails', '~> 6.0'
gem 'kramdown', '~> 1.4.1'
gem 'pg', '~> 0.17.1'
gem 'rack-timeout', '~> 0.0.4'
gem 'rails', '~> 4.2'
gem 'ranked-model', '~> 0.4.0'
gem 'dalli', '~> 2.7.2'
gem 'rmagick', '~> 2.13.3'
gem 'sass-rails', '~> 5.0.0'
gem 'sidekiq', '< 4'
gem 'simple_form', '~> 3.4'
gem 'sinatra', '~> 1.4', require: nil
gem 'slim-rails', '~> 3.1'
gem 'sprig', '~> 0.1.6'
gem 'sunspot_rails', '~> 2.2'
gem 'tinymce-rails', '~> 4.6'
gem 'turbolinks', '~> 2.5'
gem 'uglifier', '>= 1.3.0'
gem 'unicorn', '~> 4.8.0'
gem 'smart_listing', '~> 1.1.2'
gem 'font-awesome-sass', '~> 4.3.2.1'
gem 'seed_dump', '~> 3.2.2'
gem 'nokogiri', '~> 1.6.8'
gem 'rtesseract', '~> 2.0', '>= 2.0.1'
gem 'similar_text', '~> 0.0.4'
gem 'whatlanguage', '~> 1.0', '>= 1.0.6'
gem 'jquery-datatables-rails', '~> 3.3.0'
gem 'therubyracer', platforms: :ruby
gem 'will_paginate', '~> 3.1'
gem 'eventmachine', '~> 1.0.4'
gem 'awesome_print'

group :development do
  gem 'annotate', '~> 2.6.5'
  gem 'quiet_assets', '~> 1.0.3'
  gem 'spring', '~> 1.1.3'
  gem 'sunspot_solr', '~> 2.1.1'
  gem 'progress_bar'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :development, :test do
  gem 'factory_girl_rails', '~> 4.4'
  gem 'rb-fsevent'
  gem 'rspec-rails', '~> 3.0'
  gem 'spring-commands-rspec', '~> 1.0.2'
end

group :test do
  gem 'capybara', '~> 2.3.0'
  gem 'shoulda-matchers', '~> 2.6.2'
end
